server:
  port: 8800
spring:
  cloud:
    config:
      server:
        git:
         uri:  file:///D:/SpringProject/configuration-files
          search-paths:
           - '{application}'
          skip-ssl-validation: true
          clone-on-start: true



